### ISSUE TITLE
Top-nav component: Ability to right-click and see browser options: 1) open in a new tab; 2) copy url address

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/hakawati#169]
**Current behavior**
When I right-click on an item in the main navigation menu (Data, Maps, Profile), I am not able to open the page on a new tab.

**To Reproduce**
1. Go to main app page and view the main nav menu
2. Right-click on an item (Data, Maps, Profile icon)
3. See options: Lookup, copy, etc

![image](https://user-images.githubusercontent.com/4407063/91658950-c35b7400-eacc-11ea-904e-2a5cb966674a.png)

**Expected behavior**
For example, if I click on a tab in Github, I see these options to open in a new tab:
![image](https://user-images.githubusercontent.com/4407063/91658988-0289c500-eacd-11ea-8cee-4f4e8847b276.png)

I would like to see these options to option in a new tab when I click on a new page (new page = has a different URL)

Maybe the solution is to make each main nav link a link? Reference: https://javascript.info/default-browser-action

**Comment by ninetteadhikari** [comment]
after the hakawati [PR](https://github.com/hikaya-io/hakawati/pull/409) is merged, some FE changes need to be made for the right click to work
