### ISSUE TITLE
Allow users to view a summary of columns to `hide/display` when they click on the `Hide fields` checkbox on the toolbar

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/hakawati#386]
## Acceptance Criteria

GIVEN I'm a logged in user with Metrics activated

AND I click on a Project and view the Results Framework (Objectives page)

THEN I should see a toolbar (that remains fixed and not scrollable) above the spreadsheet view called `Hide fields` when all fields are displaying and `X hidden fields` when there are X number of fields that are hidden

AND when I click on `Hide field`, I should see a dropdown with a list of all the column names

AND when I un-select/select fields to display, the column should display or be hidden from the spreadsheet view including the `X number of fields` should be updated to reflect the number of fields currently hidden

Here is a walk through the functionality:
![hidden-columns](https://user-images.githubusercontent.com/4407063/204334872-4e8aa840-a4ae-4fc9-9acd-2ba049244ba0.gif)

## Note to dev
- Figma link (see `New toolbar` section): https://www.figma.com/file/2bizWQnCDp0r5RZzrM25jX/Dots?node-id=3827%3A12587&t=ry75BJeanuvh9uAt-1 
- The toggle component was designed around the `h-checkbox` with button styling
- A user will still be able to right-click on a specific column header and hide the selected column. Using the summary columns dropdown a user can select a column to be displayed again.
- For the toolbar, please follow the current styling on the column header in hakawati. I'm currently playing around with colors on the figma screens

**Comment by ninetteadhikari** [comment]
@michaelbukachi as you work on this ticket, is it possible to make the spreadsheet header row fixed? so that when the table is too long, user can scroll down and can still see the header row.

**Comment by andrewtpham** [comment]
Hey @michaelbukachi sorry for the styling changes in the GIF, I've updated the GIF and the figma screens. Please keep with the same styling. I've updated notes under ##Note to Dev section
