### ISSUE TITLE
Research package version changes when using `-alpha` in testing if hakawati works with Dots as expected

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/hakawati#419]
Package version is failing because the version check can't see the difference between version: "0.2.21-alpha03", which i think versioning cannot read from the -alpha03 so we can go ahead and merge this. I'll create a separate issue to investigate updating the check to handle these alpha cases for @myugetsu to look into

_Originally posted by @andrewtpham in https://github.com/hikaya-io/hakawati/issues/418#issuecomment-1440280002_

**Comment by andrewtpham** [comment]
Hey @myugetsu it looks like the hakawati check is failing for the common package upgrade. See this latest PR with the failed check: https://github.com/hikaya-io/hakawati/actions/runs/4683862700/jobs/8303033622?pr=426

**Comment by amosnjoroge** [comment]
@myugetsu Please check the failing pipeline.
