### ISSUE TITLE
Include `edit results` when a row has existing data added

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/hakawati#422]
**Is your feature request related to a problem? Please describe.**
Currently only `add results` is available for when there is no data and when there is existing data. We would like to have the ability to change the menu item label based on these two cases.

Note to dev: Is there a better way to handle labels like this directly in Dots? I find that these labels are app specific and we shouldn't have them in hakawati. For starters, I'd like the labels to be managed from the en.js in Dots so maybe hakawati can have some placeholder instead? What do you think @michaelbukachi?

**Acceptance Criteria**

**Additional context**
This is related to a comment: https://github.com/hikaya-io/dots/pull/1846#issuecomment-1445050156

**Comment by michaelbukachi** [comment]
@andrewtpham We will have to provide a property on the spreadsheet to allow changing of labels.

**Comment by ninetteadhikari** [comment]
This is already estimated in the FE ticket: https://github.com/hikaya-io/dots/issues/1961
